CREATE TABLE IF NOT EXISTS animal(
    animal_id INTEGER PRIMARY KEY AUTOINCREMENT,
    region TEXT,
    register_date TEXT,
    found_place TEXT,
    status TEXT,
    notice_id TEXT,
    notice_start TEXT,
    notice_end TEXT,
    breed TEXT,
    color TEXT,
    age TEXT,
    weight TEXT,
    gender TEXT,
    neutered TEXT,
    feature TEXT,
    shelter_name TEXT,
    shelter_phone TEXT,
    shelter_road_addr TEXT,
    shelter_lot_addr TEXT,
    shelter_zip TEXT,
    authority TEXT,
    note TEXT,
    image_url TEXT,
    thumbnail_url TEXT,
    lat REAL,
    lon REAL
);